config/routes.rb
Rails.application.routes.draw do

  root 'home#show'

  resources :item
  
  get 'matt' => 'home#matt'
  post 'matt' => 'home#post_matt'
  patch 'matt' => 'home#post_matt'

end

app/models/cutoff_date.rb
class CutoffDate < ActiveRecord::Base
end

app/models/item.rb
class Item < ActiveRecord::Base
    def self.to_csv
        attributes = %w{name created_at status user} #customize columns here
    
        CSV.generate(headers: true) do |csv|
              csv << attributes
              all.each do |item|
                    csv << attributes.map{ |attr| item.send(attr) }
              end
        end
    end
    
    def self.search(search)
        if search
            where('name LIKE ?', "%#{search}%")
        else
            all
        end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    http_basic_authenticate_with name: Rails.application.secrets.admin_username, password: Rails.application.secrets.admin_password, except: [:show]
    
    def show
        # shows leaderboard
        # items = Item.where("created_at >= ?", 1.week.ago.utc)
        cutoff_record = CutoffDate.order("created_at").last
        if cutoff_record
            @cutoff = cutoff_record.date
        end
        if not @cutoff
            today = Date.today.in_time_zone("Central Time (US & Canada)")
            if not today.friday? or today <= today.noon
                items = Item.where("created_at >= ?", today.beginning_of_week(:friday).noon.in_time_zone("UTC"))
            else
                items = Item.where("created_at >= ?", today.yesterday.beginning_of_week(:friday).noon.in_time_zone("UTC"))
            end
        else
            items = Item.where("created_at >= ?", @cutoff.in_time_zone("UTC"))
        end
        users = ["Adam W.", "Andy K.", "Anthony D.", "Brian B.", "Damien O.", "Daniel W.", "Dennis W.", "Heamen J.", "Jacob M.", "Jamie O.", "Justin M.", "Lucas Q.", "Mark B.", "Michael P.", "Tommie N.", "Matt K."]
        users = users.sort
        @count = {}
        users.each do |user|
            @count[user] = 0
        end
        @total = 0
        items.each do |item|
            users.each do |user2|
                if item.user == user2
                    @count[user2] += 1
                    @total += 1
                end
            end
        end
        # people.sort_by { |name, age| age }
        @count = @count.sort_by { |user, amount| -amount }
    end
    
    def matt
        @cutoff_date = CutoffDate.order("created_at").last
        if @cutoff_date
            @cutoff_date[:date] = @cutoff_date[:date].in_time_zone("Central Time (US & Canada)")
        end
        @cutoff_date ||= CutoffDate.new
    end
    
    def post_matt
        cutoff = CutoffDate.new(cutoff_date_params)
        Time.zone = "Central Time (US & Canada)"
        date = Time.zone.parse(cutoff_date_params[:date])
        Time.zone = "UTC"
        cutoff.date = date
        if cutoff.save
            flash[:success] = "Cutoff (" + date.to_s + ") saved successfully."
        else
            flash[:error] = "Cutoff date not saved, check with Adam."
        end
        redirect_to root_path
    end

    private
    def cutoff_date_params
        params.require(:cutoff_date).permit(:date)
    end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
    http_basic_authenticate_with name: Rails.application.secrets.admin_username, password: Rails.application.secrets.admin_password, except: [:index, :show, :new, :create]
    
    def index
        @items = Item.search(params["cn"]).paginate(:page => params[:page], :per_page => 20).order('created_at DESC')
        @cert_count = Item.count
        @page = params[:page]
        respond_to do |format|
            format.html
            format.csv { send_data Item.all.to_csv, filename: "certs-#{Date.today}.csv" }
        end
    end
    
    def show
        @item = Item.find(params[:id])
    end
    
    def new
        @user= ""
        @certs = ""
        @status = ""
    end
    
    def create
        new_item_params = item_params
        successful = true
        if item_params["name"].empty? or item_params["user"].empty? or item_params["status"].empty?
            @certs = item_params["name"]
            @user = item_params["user"]
            @status = item_params["status"]
            flash[:danger] = "Please fill out all fields."
            render 'new'
        else
            item_params["name"].split(/[\r\n]+ /x).each do |new_item|
                new_item_params["name"] = new_item
                item = Item.new(new_item_params)
                successful = successful and item.save
            end
            if successful
                flash[:success] = "Cert(s) saved successfully."
            else
                flash[:error] = "One or more certs did not save successfuly, check with Adam."
            end
            redirect_to root_path
        end
    end
    
    def destroy
        Item.find(params[:id]).destroy
        flash[:success] = "Cert deleted"
        redirect_to root_path
    end
    
    private
    def item_params
        params.require(:item).permit(:user, :name, :status)
    end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/item_helper.rb
module ItemHelper
end

app/views/home/matt.html.erb
<%= form_for @cutoff_date, url: matt_path do |f| %>
    <div class="form-group">
        <%= f.datetime_select :date %>
        <%= f.submit "Submit" %>
    </div>
<% end %>

app/views/home/show.html.erb
<div>
    <h1>
        Leaderboard
    </h1>
    <% if not @cutoff %>
        <h3>Since noon last Friday (Central Time (US & Canada))</h3>
    <% else %>
        <h3>Since <%= @cutoff.in_time_zone("Central Time (US & Canada)").to_s(:long_ordinal) %> (Central Time (US & Canada))</h3>
    <% end %>
    <table class="table table-striped">
        <% @count.each do |key, value| %>
        <tr>
            <td><%= key %></td>
            <td><%= value %></td>
        </tr>
        <% end %>
    </table>
    <br/>
    <h1>Total: <%= @total %></h1>
</div>

app/views/item/index.html.erb
<div>
    <p>
        <h3>Total: <%= @cert_count %></h3>
        <a class="link" href="/item.csv">Download as CSV</a>
    </p>
    <%= form_tag item_index_path, :method => 'get', :id => "cn_search" do %>
    <p>
        <%= text_field_tag :cn, params[:cn], :placeholder => "Common Name" %>
        <%= submit_tag "Search", :name => nil %>
        <%= link_to 'Clear', item_index_path %>
    </p>
    <% end %>
    <%= will_paginate @items, :renderer => BootstrapPagination::Rails %>
    <table class="table table-striped">
        <% @items.each do |item| %>
        <tr class="row">
            <td><%= item.id %></td>
            <td><%= item.name %></td>
            <td><%= item.created_at.in_time_zone("Central Time (US & Canada)") %></td>
            <td><%= item.status %></td>
            <td><%= item.user %></td>
            <td><%= link_to 'Delete', item, :method => :delete, data: {confirm: "Are you sure?"} %></td>
        </tr>
        <% end %>
    </table>
</div>

app/views/item/new.html.erb
<%= form_for :item, url: item_index_path do |f| %>
    <div class="form-group">
        <p>
            <label class="" for="user">Select Name:</label>
            <select name="item[user]" class="form-control" id="item_user" required>
                <option value="">Please select</option>
                <option <%= @user.eql?("Adam W.") ? 'selected="selected"' : "" %>>Adam W.</option>
                <option <%= @user.eql?("Andy K.") ? 'selected="selected"' : "" %>>Andy K.</option>
                <option <%= @user.eql?("Anthony D.") ? 'selected="selected"' : "" %>>Anthony D.</option>
                <option <%= @user.eql?("Brian B.") ? 'selected="selected"' : "" %>>Brian B.</option>
                <option <%= @user.eql?("Damien O.") ? 'selected="selected"' : "" %>>Damien O.</option>
                <option <%= @user.eql?("Daniel W.") ? 'selected="selected"' : "" %>>Daniel W.</option>
                <option <%= @user.eql?("Dennis W.") ? 'selected="selected"' : "" %>>Dennis W.</option>
                <option <%= @user.eql?("Heamen J.") ? 'selected="selected"' : "" %>>Heamen J.</option>
                <option <%= @user.eql?("Jacob M.") ? 'selected="selected"' : "" %>>Jacob M.</option>
                <option <%= @user.eql?("Jamie O.") ? 'selected="selected"' : "" %>>Jamie O.</option>
                <option <%= @user.eql?("Justin M.") ? 'selected="selected"' : "" %>>Justin M.</option>
                <option <%= @user.eql?("Lucas Q.") ? 'selected="selected"' : "" %>>Lucas Q.</option>
                <option <%= @user.eql?("Mark B.") ? 'selected="selected"' : "" %>>Mark B.</option>
                <option <%= @user.eql?("Matt K.") ? 'selected="selected"' : "" %>>Matt K.</option>
                <option <%= @user.eql?("Michael P.") ? 'selected="selected"' : "" %>>Michael P.</option>
                <option <%= @user.eql?("Tommie N.") ? 'selected="selected"' : "" %>>Tommie N.</option>
            </select>
        </p>
        <p>
            <%= f.label "Cert Common Name(s)" %><br>
            <textarea placeholder="List of certs, one per line" name="item[name]" class="form-control" rows="5" id="certs" required><%= @certs %></textarea>
        </p>
        <p>
            <label class="" for="status">Select Status:</label>
            <select name="item[status]" class="form-control" id="item_status" required>
                <option value="">Please select</option>
                <option <%= @status.eql?("Already Replaced") ? 'selected="selected"' : "" %>>Already Replaced</option>
                <option <%= @status.eql?("App Team Replacing") ? 'selected="selected"' : "" %>>App Team Replacing</option>
                <option <%= @status.eql?("Decommissioned") ? 'selected="selected"' : "" %>>Decommissioned</option>
                <option <%= @status.eql?("Replaced") ? 'selected="selected"' : "" %>>Replaced</option>
            </select>
        </p> 
        <p>
            <input class="button" type="submit" name="commit" value="Save Cert(s)" id="submit">
        </p>
    </div>
<% end %>

app/views/item/show.html.erb
<div>
    <p>Item: <%= @item.name %></p>
    <p>Users: <%= @item.user %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cert Tracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="container-fluid">
    <ul class="nav nav-tabs">
        <li <%= current_page?("/") ? "class=active" : "" %>><a href="/">Leaderboard</a></li>
        <li <%= current_page?("/item") ? "class=active" : "" %>><a href="/item">Certs</a></li>
        <li <%= current_page?("/item/new") ? "class=active" : "" %>><a href="/item/new">Log New Certs</a></li>
    </ul>
    <br/>
    <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
</body>
</html>